export {default as MainPage} from './MainPage'
export {default as StockPage} from './StockPage'
export {default as MuseumPage} from './MuseumPage'
export {default as LibraryPage} from './LibraryPage'
export {default as AnyEventPage} from './AnyEventPage'
export {default as EventPage} from './EventPage'
export * from './any-museum-page'
export * from './about-page'
export * from './office-page'